services:
  - type: web
    name: pfc-menu
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
